SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS telefones;
DROP TABLE IF EXISTS entrega_encomenda;
DROP TABLE IF EXISTS entregas;
DROP TABLE IF EXISTS endereco;
DROP TABLE IF EXISTS encomendas;
DROP TABLE IF EXISTS veiculos;
DROP TABLE IF EXISTS motoristas;
DROP TABLE IF EXISTS clientes;

SET FOREIGN_KEY_CHECKS = 1;